name: CloudFormation Guard Validate

on:
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: CloudFormation Guard validate
    steps:
      - name: CloudFormation Guard validate
        uses: dannyvassallo/cloudformation-guard@action-v0.0.25
        with:
          rules: 'resources/validate/rules'
          data: 'resources/validate/data'
