name: CloudFormation Guard validate

on:
  push:

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions: write-all
    name: CloudFormation Guard validate
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          checkout: false
          rules: 'resources/validate/rules'
          data: 'resources/validate/data'
